#!/bin/bash

# Путь установки
TARGET_APP="/Applications/BulbaGPT"

# Определяем реального пользователя (не root)
CURRENT_USER=$(scutil <<< "show State:/Users/ConsoleUser" | awk '/Name :/ { print $3 }')

# Если пользователь найден и это не экран входа
if [ -n "$CURRENT_USER" ] && [ "$CURRENT_USER" != "loginwindow" ]; then
    # Отдаем папку пользователю
    chown -R "$CURRENT_USER:staff" "$TARGET_APP"
fi

# Даем права на запись (755)
chmod -R 755 "$TARGET_APP"

exit 0